name = "life-recorder"
compatibility_date = "2024-10-17"

[env.production]
name = "life-recorder"

# Cloudflare Pages 配置
[pages]
# 构建命令
build_command = "CF_PAGES=1 npm run build"
# 输出目录
output_directory = "out"
# 根目录
root_directory = "."
