# Cloudflare Pages 配置文件
name = "life-recorder"
compatibility_date = "2024-01-15"

# 构建配置
[build]
command = "npm run build"
cwd = "."

# 环境变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://life-recorder.pages.dev"
