services:
  - type: web
    name: life-recorder-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: life-recorder-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: life-recorder-db
    plan: free
    region: oregon

